# Generated by Django 4.2.16 on 2024-10-30 08:15

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_location', models.CharField(max_length=200)),
                ('product_brand', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=product.models.upload_to)),
                ('product_condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', to_field='name')),
                ('product_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory.subcategory', to_field='name')),
            ],
        ),
    ]
