# Generated by Django 4.2.16 on 2024-10-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brands',
            new_name='product_brands',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='condition',
            new_name='product_condition',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='product_location',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='product_sub_category',
        ),
    ]
