# Generated by Django 4.2.16 on 2024-10-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_alter_subcategory_name'),
        ('category', '0002_alter_category_name'),
        ('product', '0003_rename_brands_product_product_brands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', to_field='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory.subcategory', to_field='name'),
        ),
    ]
